apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-resourcequota
spec:
  hard:
    pods: "100"
    cpu: "1000m"

#Use to limit the amount of resources, or/and amount of pod running at any given time

#Using resource quota is a good way to stop applications in one namespace from grabbing
  #too many resources and starving those in other parts of the cluster