apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 5000
  selector:
    app: ghostpipeline
  type: LoadBalancer
  